#ifndef _BOARD_H
#define _BOARD_H

#include <avr/io.h>

#define SEGMENT_LCD_DATA_WIDTH 4
#define SEGMENT_LCD_COM_COUNT 4

#define SEGMENT_LCD_COM0_SETZ PORTA.DIRCLR = 0x80 // PA7 off
#define SEGMENT_LCD_COM0_SET0 PORTA.OUTCLR = 0x80; PORTA.DIRSET = 0x80 // PA7 set to 0
#define SEGMENT_LCD_COM0_SET1 PORTA.OUTSET = 0x80; PORTA.DIRSET = 0x80 // PA7 set to 1

#define SEGMENT_LCD_COM1_SETZ PORTA.DIRCLR = 0x40 // PA6 off
#define SEGMENT_LCD_COM1_SET0 PORTA.OUTCLR = 0x40; PORTA.DIRSET = 0x40 // PA6 set to 0
#define SEGMENT_LCD_COM1_SET1 PORTA.OUTSET = 0x40; PORTA.DIRSET = 0x40 // PA6 set to 1

#define SEGMENT_LCD_COM2_SETZ PORTA.DIRCLR = 0x08 // PA3 off
#define SEGMENT_LCD_COM2_SET0 PORTA.OUTCLR = 0x08; PORTA.DIRSET = 0x08 // PA3 set to 0
#define SEGMENT_LCD_COM2_SET1 PORTA.OUTSET = 0x08; PORTA.DIRSET = 0x08 // PA3 set to 1

#define SEGMENT_LCD_COM3_SETZ PORTA.DIRCLR = 0x04 // PA2 off
#define SEGMENT_LCD_COM3_SET0 PORTA.OUTCLR = 0x04; PORTA.DIRSET = 0x04 // PA2 set to 0
#define SEGMENT_LCD_COM3_SET1 PORTA.OUTSET = 0x04; PORTA.DIRSET = 0x04 // PA2 set to 1

void HALInit(void);

#endif
